# GENERATED by scripts/gen-sdk-types.mts from gaiadesk-client's JSON Schema — do not edit.
# The result, error, request and event types of gaiadesk-client and `gaiadesk-cli --json`.
from __future__ import annotations

import sys
from typing import Any, Dict, List, Literal, Optional, TypedDict, Union

if sys.version_info >= (3, 11):
    from typing import NotRequired
else:  # typing_extensions before Python 3.11
    from typing_extensions import NotRequired


class AccountRevoked(TypedDict):
    """`token revoke --account --json`."""
    desk: str
    message: str
    ok: bool


class AgentCheck(TypedDict):
    """`agent-connect --json`."""
    desk_id: str
    ok: bool
    screenshot: "ScreenSize"


class AuditEvent(TypedDict):
    """One entry of a desk's agent audit log, as its owner reads it."""
    action: str
    at_ms: int
    bytes: NotRequired[int]
    cwd: NotRequired[Optional[str]]
    desk: str
    detail: str
    duration_ms: NotRequired[Optional[int]]
    exit_code: NotRequired[Optional[int]]
    token: str
    token_id: str


class AuditLog(TypedDict):
    """`audit --json`, newest first."""
    events: List["AuditEvent"]


Button = Literal["left", "right", "middle"]
"""A mouse button."""


class CopyFailure(TypedDict):
    message: str
    path: str


CopyProgress = Union["CopyProgress_FileDone", "CopyProgress_FileFailed", "CopyProgress_Bytes"]
"""What a copy is doing, as it goes (`Desk::cp_up_with_progress`)."""


class CopyResult(TypedDict):
    """What a copy did — the `--json` summary."""
    bytes: int
    desk: str
    destination: str
    direction: str
    dirs: int
    failed: List["CopyFailure"]
    files: int
    resumed_bytes: int
    seconds: float


class DeskStats(TypedDict):
    """What a desk is doing right now (`gaiadesk-cli stats`,
`DataMessage::Stats`). Every number is a snapshot taken when
asked."""
    cpu_percent: float
    cpus: int
    disks: NotRequired[List["DiskStat"]]
    hostname: str
    jobs_running: int
    load: NotRequired[Optional[List[float]]]
    mem_free_mb: int
    mem_total_mb: int
    os: str
    os_version: NotRequired[str]
    uptime_secs: int


class Device(TypedDict):
    """One desk, as listed."""
    anytime: NotRequired[Optional[bool]]
    app_version: NotRequired[Optional[str]]
    desk_id: str
    last_failure: NotRequired[Union["ReachFailure", None]]
    last_ok: NotRequired[Union["ReachSuccess", None]]
    last_seen: NotRequired[Optional[int]]
    name: NotRequired[Optional[str]]
    online: NotRequired[Optional[bool]]
    os: NotRequired[Optional[str]]
    owner: NotRequired[Optional[str]]
    probe: NotRequired[Union["ProbeResult", None]]
    reachable: NotRequired[Optional[bool]]
    signal_idle_secs: NotRequired[Optional[int]]
    sources: List[str]


class DeviceList(TypedDict):
    """`devices --json`."""
    devices: List["Device"]
    notes: List[str]
    sources: List[str]


Direction = Literal["up", "down", "left", "right"]
"""Which way the content moves."""


class Disconnected(TypedDict):
    """`disconnect --json`."""
    closed: List[str]


class DiskStat(TypedDict):
    """One volume in `DeskStats`."""
    free_mb: int
    mount: str
    total_mb: int


class Error(TypedDict):
    """Why a call did not succeed: one of six `ErrorKind`s, a sentence for a
person, the finer cause where there is one, and the desk it concerned.

Its serde form is the object inside `gaiadesk-cli`'s `--json` error
envelope (`ErrorEnvelope`): `{"kind", "message", "reason"?, "desk"?}`."""
    desk: NotRequired[Optional[str]]
    kind: "ErrorKind"
    message: str
    reason: NotRequired[Optional[str]]


class ErrorEnvelope(TypedDict):
    """`{"error": {…}}` — what every `--json` command prints when it fails."""
    error: "Error"


ErrorKind = Union[Literal["usage"], Literal["refused"], Literal["unreachable"], Literal["connection_lost"], Literal["failed"], Literal["protocol"]]
"""The six kinds a program branches on. Stable: a new kind would be a
breaking change, so match with a wildcard arm anyway."""


ExecEvent = Union["ExecEvent_Stdout", "ExecEvent_Stderr", "ExecEvent_Note", "ExecEvent_Exit", "ExecEvent_Error"]
"""One event of a streamed command (`Desk::exec_stream`) —
`gaiadesk-cli exec --json-stream` prints one per line (all but `note`)."""


class ExecExit(TypedDict):
    """`ExecResult` without the output — the last event of a stream."""
    desk: str
    duration_ms: int
    error: NotRequired[Union["Error", None]]
    exit: int
    mode: NotRequired[Optional[str]]
    notes: List[str]
    remote_code: NotRequired[Optional[int]]
    route: NotRequired[Optional[str]]
    shell: NotRequired[Optional[str]]
    timed_out: bool


class ExecResult(TypedDict):
    """How one command ended — `gaiadesk-cli exec --json`'s object."""
    desk: str
    duration_ms: int
    error: NotRequired[Union["Error", None]]
    exit: int
    mode: NotRequired[Optional[str]]
    notes: List[str]
    remote_code: NotRequired[Optional[int]]
    route: NotRequired[Optional[str]]
    shell: NotRequired[Optional[str]]
    stderr: str
    stdout: str
    timed_out: bool
    truncated: bool


class ExecSpec(TypedDict):
    """One command to run on a desk (`Desk::exec`).

`command` is ONE command line, given to the shell verbatim; `argv` is an
argument vector, each entry quoted for the shell so the program receives
exactly it. Build it with `ExecSpec::command` or `ExecSpec::argv`."""
    argv: NotRequired[List[str]]
    command: NotRequired[Optional[str]]
    cwd: NotRequired[Optional[str]]
    shell: NotRequired["Shell"]
    stdin: NotRequired[Optional[str]]
    timeout_secs: NotRequired[Optional[float]]


class Forward(TypedDict):
    """Forwards that are running (`Desk::forward_start`)."""
    desk: str
    forward_id: str
    listening: List["ForwardListening"]


class ForwardListening(TypedDict):
    """One port listening (`forward --json`'s `{"event":"listening",…}`)."""
    desk: str
    local_port: int
    remote_host: str
    remote_port: int


class ForwardSpec(TypedDict):
    """One port to forward: `localhost:<local_port>` here → `<remote_host>:<remote_port>` as the desk reaches it."""
    local_port: int
    remote_host: str
    remote_port: int


class ForwardStopped(TypedDict):
    """A forward that ended on purpose (`Client::forward_stop`)."""
    forward_id: str
    local_ports: List[int]


class Job(TypedDict):
    """A background job on a desk."""
    by: NotRequired[str]
    command: str
    ended_at_ms: NotRequired[Optional[int]]
    enforcement: NotRequired[List[str]]
    exit_code: NotRequired[Optional[int]]
    limits: NotRequired[Union["JobLimits", None]]
    log_bytes: NotRequired[int]
    name: str
    pid: NotRequired[Optional[int]]
    started_at_ms: int
    state: str


class JobLimits(TypedDict):
    """What a background job may use, and whether the desk stays awake for it
(`DataMessage::JobStart`'s `limits`). Every field optional and
off the wire when unset, so a start without limits is byte for byte what
it was. A desk lists `feature::JOB_LIMITS` when it enforces them;
a desk before that ignores the field, which is why a CLI refuses to send
caps to one."""
    cpu_percent: NotRequired[Optional[int]]
    keep_awake: NotRequired[Optional[bool]]
    mem_mb: NotRequired[Optional[int]]
    priority: NotRequired[Optional[str]]


class JobList(TypedDict):
    """`ps --json`."""
    jobs: List["Job"]


JobLogEvent = Union["JobLogEvent_Output", "JobLogEvent_End", "JobLogEvent_Interrupted", "JobLogEvent_Error"]
"""One event of a followed job's output (`logs -f --json`)."""


class JobLogs(TypedDict):
    """`logs --json`: a job and the end of its output."""
    job: "Job"
    output: str


class JobSpec(TypedDict):
    """A background job to start (`Desk::run_job`)."""
    command: List[str]
    cwd: NotRequired[Optional[str]]
    limits: NotRequired["JobLimits"]
    name: str


class Measurement(TypedDict):
    """`measure --json`."""
    clock_offset_ms: NotRequired[Optional[float]]
    clock_uncertainty_ms: NotRequired[Optional[float]]
    desk: str
    rtt_ms: NotRequired[Union["RoundTrip", None]]
    sent: int


class MeshIp(TypedDict):
    """`mesh ip`: one desk's address; `renamed_to` when the id asked for is a
desk's old one (it answers on Mesh for 7 days after a change)."""
    desk_id: str
    mesh_ip: str
    renamed_to: NotRequired[Optional[str]]


class MeshPeer(TypedDict):
    """A desk's row in `mesh status`: its id (the Mesh node name IS the desk id)
and its stable Mesh address."""
    desk_id: str
    mesh_ip: NotRequired[Optional[str]]
    online: bool
    os: str


class MeshSelf(TypedDict):
    """This machine on the Mesh."""
    desk_id: str
    mesh_ip: NotRequired[Optional[str]]


class MeshStatus(TypedDict):
    """`mesh status`: this machine and its peers."""
    peers: List["MeshPeer"]
    self: NotRequired[Union["MeshSelf", None]]


class MintResult(TypedDict):
    """`token create --json` (several desks: one token each)."""
    tokens: List["MintedToken"]


class MintSpec(TypedDict):
    """An agent token to mint (`Desk::mint_token`)."""
    cwd: NotRequired[Optional[str]]
    expires_secs: int
    low_priv: NotRequired[bool]
    name: str
    scopes: List[str]


class MintedToken(TypedDict):
    """One minted token. `secret` is the token itself — shown once."""
    desk: str
    secret: str
    token: "TokenInfo"


class ProbeResult(TypedDict):
    """One desk's probe."""
    connect_ms: NotRequired[Optional[int]]
    dialled: bool
    error: NotRequired[Optional[str]]
    hostname: NotRequired[Optional[str]]
    kind: NotRequired[Optional[str]]
    ok: bool
    os: NotRequired[Optional[str]]
    route: NotRequired[Optional[str]]
    rtt_ms: NotRequired[Optional[int]]


class ReachFailure(TypedDict):
    """A connect that did not."""
    at: int
    kind: str
    message: str


class ReachSuccess(TypedDict):
    """A connect that worked."""
    at: int
    connect_ms: NotRequired[Optional[int]]
    route: str
    rtt_ms: NotRequired[Optional[int]]


class Revoked(TypedDict):
    """`token revoke --json`."""
    revoked: str
    stopped_sessions: int


class RoundTrip(TypedDict):
    """Round trips, ms."""
    max: float
    n: int
    p50: float
    p95: float


class ScreenImage(TypedDict):
    """A picture of the screen."""
    data_base64: str
    height: NotRequired[Optional[int]]
    media_type: str
    width: NotRequired[Optional[int]]


class ScreenResult(TypedDict):
    """What one screen action returned: words, and a picture when it took one."""
    image: NotRequired[Union["ScreenImage", None]]
    text: str


class ScreenSize(TypedDict):
    height: int
    width: int


Shell = Union[Literal["default"], Literal["none"], Literal["sh"], Literal["cmd"], Literal["pwsh"]]
"""Which shell runs a command on the desk."""


class StatsReport(TypedDict):
    """`stats --json`: the desk's own figures."""
    cpu_percent: float
    cpus: int
    desk: str
    disks: NotRequired[List["DiskStat"]]
    hostname: str
    jobs_running: int
    load: NotRequired[Optional[List[float]]]
    mem_free_mb: int
    mem_total_mb: int
    os: str
    os_version: NotRequired[str]
    uptime_secs: int


class TokenInfo(TypedDict):
    """One agent token as its desk's owner sees it: everything but the secret."""
    cwd: NotRequired[Optional[str]]
    expires_at_ms: int
    id: str
    issued_at_ms: int
    label: str
    last_used_ms: NotRequired[Optional[int]]
    low_priv: NotRequired[bool]
    revoked: NotRequired[bool]
    scopes: NotRequired[List[str]]


class TokenList(TypedDict):
    """`token list --json`."""
    tokens: List["TokenInfo"]


class VersionInfo(TypedDict):
    """`--version --json`."""
    features: List[str]
    json_shapes: List[str]
    mcp_protocol_versions: List[str]
    name: str
    version: str



# Inline variants (after the types they extend: a base class must exist first).

class CopyProgress_FileDone(TypedDict):
    event: Literal["file_done"]
    path: str
    resumed: int
    size: int


class CopyProgress_FileFailed(TypedDict):
    event: Literal["file_failed"]
    message: str
    path: str


class CopyProgress_Bytes(TypedDict):
    done: int
    event: Literal["bytes"]
    path: str
    size: int


class ExecEvent_Stdout(TypedDict):
    """Output on stdout. `data` is the text this chunk completes (a character
split across chunks waits for its end); `bytes` (not serialized) are
the exact bytes of the chunk."""
    data: str
    event: Literal["stdout"]


class ExecEvent_Stderr(TypedDict):
    """Output on stderr (as `stdout`)."""
    data: str
    event: Literal["stderr"]


class ExecEvent_Note(TypedDict):
    """A line of this client's about the run (it is waiting for the desk…)."""
    event: Literal["note"]
    message: str


class ExecEvent_Exit(ExecExit):
    """It ended (always the last event of a run that started)."""
    event: Literal["exit"]


class ExecEvent_Error(TypedDict):
    """It never ran, or the connection went: `exit` is the CLI's exit code."""
    error: "Error"
    event: Literal["error"]
    exit: int


class JobLogEvent_Output(TypedDict):
    data: str
    event: Literal["output"]


class JobLogEvent_End(TypedDict):
    """The job ended (or, not following, the output so far was all sent)."""
    event: Literal["end"]
    job: "Job"


class JobLogEvent_Interrupted(TypedDict):
    """Following was stopped here; the job goes on."""
    event: Literal["interrupted"]


class JobLogEvent_Error(TypedDict):
    error: "Error"
    event: Literal["error"]
